[build]
  command = "cd project && npm run build"
  publish = "project/dist"

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms.html"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
